apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-entraid
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_LRS
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - mfsymlinks
  - nobrl