apiVersion: v1
kind: Pod
metadata:
  name: test-azurefile-pod
spec:
  containers:
    - name: web-app
      image: nginx:alpine
      volumeMounts:
        - mountPath: "/mnt/azure"
          name: azurefile-volume
  volumes:
    - name: azurefile-volume
      persistentVolumeClaim:
        claimName: azurefile-pvc